### ISSUE TITLE
Authentication against server using connectSession in parcel

### ISSUE THREAD

**Issue by GINQO** [skokenes/RxQ#64]
Running on our server, having trouble authenticating with the same credentials as used for enigma.js application.

`import { connectSession } from "rxq";`
`import { EngineVersion } from "rxq/Global";`
`import { switchMap } from "rxjs/operators";`

`const fs = require('fs');`
`const userDirectory = 'APIUSERS';`
`const userId = 'scriptload';`

`// Define the configuration for your session`
`const config = {`
    `host: "AWSOR135.ad.ginqo.com",`
    `port: 4747,`
    `appname: "engineData",`
    `isSecure: true,`
    `ca: [fs.readFileSync('./certificates/root.pem')],`
    `key: fs.readFileSync('./certificates/client_key.pem'),`
    `cert: fs.readFileSync('./certificates/client.pem'),`
    `headers: {`
        `'X-Qlik-User': UserDirectory=${encodeURIComponent(userDirectory)};` 
          `UserId=${encodeURIComponent(userId)}`,
   ` }`
`};`

`// Create a session`
`const session = connectSession(config);`

`// Get the Global Handle observable`
`const global$ = session.global$;`

`// Get the engineVersion`
`const engVer$ = global$.pipe(`
`  switchMap(h => h.ask(EngineVersion))`
`);`

`// Write the engine version to the DOM`
`engVer$.subscribe(response => {`
`  document.querySelector("#ver").innerHTML = response.qComponentVersion;`
`});`

**Comment by skokenes** [comment]
@GINQO am I okay to close this or is this still an issue?

**Comment by GINQO** [comment]
Yes you can close
